### ISSUE TITLE
Allow customization of atomic elements

### ISSUE THREAD

**Issue by piever** [piever/AlgebraOfGraphics.jl#4]
So far, one can add any atomic `AbstractSimple` element to the pipeline, however by default, when the `AbstractElement` of the algebra of graphics (a combination of `Group`, `Data`, etc...) is converted to traces, they are simply kept as metadata (see [source](https://github.com/piever/AlgebraOfGraphics.jl/blob/master/src/traces.jl)). It would be interesting to understand what other types of "atomic types" would be interesting here, and how it would be possible to overload the pipeline externally.

cc: @sethaxen, you were mentioning `Condition` for probabilistic grammar of graphics, what behavior do you expect from it?

**Comment by sethaxen** [comment]
The PGoG seems to still be a WIP (there are some inconsistencies in the preprint), and I don't understand all of it, but the basic idea is summarized as:
> A probabilistic visualization is correct if the proportions of visual elements (such as counts or areas) and their spatial placement reflect the underlying probability distribution, including any conditional probabilities or part-to-whole relationships.

An explanation of how a `Condition` might differ from `Group`:

```julia
# implicitly defines that x-axis is MPG
spec = (Lines ⊕ density) ⊗ Data(mtcars) ⊗ Select(:MPG)and y-axis must be P(MPG)
# regroups data, effectively making each y-axis P(MPG | Cyl)
plot(spec ⊗ Group(color = :Cyl))
# regroups data but scales y-axes by P(Cyl) so that the total y-axis is still P(MPG),
# but each density has a y-axis of P(MPG | Cyl) P(Cyl)
plot(spec ⊗ Condition(color = :Cyl))
```

I don't know though that a `Condition` type is what's missing. The syntax they introduce replaces variables with conditional probabilities, e.g. something like

```julia
spec = Data(mtcars) ⊗ Select(MPG, @P(MPG | Cyl) @P(Cyl))
lines(spec ⊗ Style(color = :Cyl))
```

but I find this all mind-bendy, and to be honest, I'm probably not going to sit down to sort this all out anytime soon.

**Comment by piever** [comment]
Ah OK, so basically one needs to keep in mind that there could be something that "inherits" from some `AbstractGroup`, but, in the process of grouping, also gives some metadata (like frequency of a particular group entry).

**Comment by piever** [comment]
Now there is a `context` field in `Trace` that can be used to specify how everything is interpretable, so this should be fully customizable.
